rinkinys = set(range(100))
print('Elementų skaičius:', len(rinkinys))
print('Mažiausias elementas:', min(rinkinys))
print('Didžiausias elementas:', max(rinkinys))
print('Vidutinė rinkinio reikšmė:')